Advantages of Numpy Arrays:

Allows several Mathematical Operations

Faster operations


In [2]:
import numpy as np

In [3]:

from time import process_time

In [4]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)
     

0.0


In [5]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  

end_time = process_time()

print(end_time - start_time)

0.0


In [6]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:

np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:

# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape

(4,)

In [10]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [13]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:

# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# array of a particular value
z = np.full((5,4),5)
print(z)
     

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.89906661 0.61674928 0.92323393 0.86855151]
 [0.14613811 0.78578569 0.69856483 0.03821041]
 [0.00573112 0.78093505 0.66016512 0.79781784]]


In [18]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[52 78 21 52 12]
 [10 48 26 30 35]
 [62 20 62 39 83]]


In [19]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [20]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [21]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [22]:
c = np.random.randint(10,90,(5,5))
print(c)

[[22 71 60 15 77]
 [32 40 46 46 66]
 [67 60 23 68 75]
 [89 34 81 86 11]
 [82 64 42 44 32]]


In [23]:
# array dimension
print(c.shape)

(5, 5)


In [24]:
# number of dimensions
print(c.ndim)

2


In [25]:
# number of elements in an array
print(c.size)

25


In [26]:
# checking the data type of the values in the array
print(c.dtype)

int32


In [27]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [28]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [29]:
print(a)
print(b)

[[8 0 7]
 [8 5 0]
 [7 5 6]]
[[17 12 17]
 [12 16 18]
 [18 16 15]]


In [30]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[25 12 24]
 [20 21 18]
 [25 21 21]]
[[ -9 -12 -10]
 [ -4 -11 -18]
 [-11 -11  -9]]
[[136   0 119]
 [ 96  80   0]
 [126  80  90]]
[[0.47058824 0.         0.41176471]
 [0.66666667 0.3125     0.        ]
 [0.38888889 0.3125     0.4       ]]


In [31]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [32]:
print(a)
print(b)

[[9 1 0]
 [7 6 0]
 [8 5 9]]
[[18 14 14]
 [13 19 19]
 [18 19 11]]


In [33]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[27 15 14]
 [20 25 19]
 [26 24 20]]
[[ -9 -13 -14]
 [ -6 -13 -19]
 [-10 -14  -2]]
[[162  14   0]
 [ 91 114   0]
 [144  95  99]]
[[0.5        0.07142857 0.        ]
 [0.53846154 0.31578947 0.        ]
 [0.44444444 0.26315789 0.81818182]]


In [34]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 6 5]
 [6 7 7]]
(2, 3)


In [35]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[2 6]
 [6 7]
 [5 7]]
(3, 2)


In [36]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 6 5]
 [8 8 6]]
(2, 3)


In [37]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[7 8]
 [6 8]
 [5 6]]
(3, 2)


In [38]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[9 9 4]
 [7 6 0]]
(2, 3)


In [39]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[9 9]
 [4 7]
 [6 0]]
(3, 2)
