In [1]:
import numpy as np

In [4]:
# create a matrix
matrix_1 = np.array([[12,45],[78,79]])
print(matrix_1)

[[12 45]
 [78 79]]


In [5]:
matrix_1.shape

(2, 2)

In [6]:
matrix_2 = np.array([[12,34,45],[45,56,78],[56,76,78]])
print(matrix_2)

[[12 34 45]
 [45 56 78]
 [56 76 78]]


In [7]:
matrix_2.shape

(3, 3)

In [8]:
# creating matrix with random value
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.17608803 0.98438423 0.7668072 ]
 [0.59721248 0.1319171  0.55374827]
 [0.10595642 0.62034964 0.69325821]]


In [9]:
# creating matrix with random integers
random_int = np.random.randint(100, size=(4,4))
print(random_int)

[[83 88 71 91]
 [67 34 17 77]
 [19 71 18 45]
 [94 64 58 97]]


In [10]:
# create matrix with one
one_matrix = np.ones((4,4), dtype='int')
print(one_matrix)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [12]:
# NUll matrix or Zero matrix
zero_matrix = np.zeros((4,5))
print(zero_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# identity matrix
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# transpose of a matrix
a = np.random.randint(100, size = (4,5))
print(a)

[[79 40 76 64 77]
 [53 64 89 48 59]
 [71 90 49 53  4]
 [93 88 20 81 23]]


In [16]:
t_a = np.transpose(a)

In [17]:
print(t_a)

[[79 53 71 93]
 [40 64 90 88]
 [76 89 49 20]
 [64 48 53 81]
 [77 59  4 23]]
