In [1]:
import numpy as np

In [2]:
# Creating two matrix
a = np.array([[3,4],[7,8]])
b = np.array([[8,8],[9,6]])

In [3]:
print(a)

[[3 4]
 [7 8]]


In [4]:
print(b)

[[8 8]
 [9 6]]


In [5]:
sum = a + b
print(sum)

[[11 12]
 [16 14]]


In [6]:
# create two matrix with random value
A = np.random.randint(10, size=(6,6))
B = np.random.randint(10, size = (6,6))

In [7]:
print(A)

[[7 5 7 7 0 5]
 [2 7 0 6 9 6]
 [7 9 8 5 2 8]
 [8 2 4 6 4 0]
 [2 6 7 1 6 3]
 [9 5 4 5 3 1]]


In [9]:
print(B)

[[6 1 0 3 1 4]
 [3 2 8 1 5 8]
 [3 2 9 3 7 4]
 [5 6 9 4 4 6]
 [1 6 9 2 0 3]
 [8 5 2 1 2 5]]


In [10]:
sum = np.add(A, B)

In [11]:
print(sum)

[[13  6  7 10  1  9]
 [ 5  9  8  7 14 14]
 [10 11 17  8  9 12]
 [13  8 13 10  8  6]
 [ 3 12 16  3  6  6]
 [17 10  6  6  5  6]]



Matrix Subtraction

In [12]:
# Creating two matrix
A = np.array([[7,7],[9,8]])
B = np.array([[6,6],[3,3]])

In [13]:
print(A)

[[7 7]
 [9 8]]


In [14]:
print(B)

[[6 6]
 [3 3]]


In [15]:
diff = A - B
print(diff)

[[1 1]
 [6 5]]


In [16]:
diff = np.subtract(A,B)
print(diff)

[[1 1]
 [6 5]]



Multiplying a matrix by a scalar

In [17]:
x = 5
y = np.random.randint(10, size=(4,4))

In [18]:
print(y)

[[7 1 0 5]
 [2 9 1 2]
 [7 4 7 6]
 [4 2 9 8]]


In [19]:
product = np.multiply(x,y)

In [20]:
print(product)

[[35  5  0 25]
 [10 45  5 10]
 [35 20 35 30]
 [20 10 45 40]]



Multiplying 2 Matrices

In [21]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [22]:
print(matrix_3)

[[2 2 3]
 [0 2 3]
 [4 1 1]]


In [24]:
print(matrix_4)

[[2 3 0 1]
 [2 2 1 0]
 [0 1 1 3]]


In [25]:
product = np.dot(matrix_3, matrix_4)

In [26]:
print(product)

[[ 8 13  5 11]
 [ 4  7  5  9]
 [10 15  2  7]]


Element wise Matrix Multiplication

In [27]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [28]:
print(matrix_3)

[[0 2 2]
 [2 4 2]
 [2 4 3]]


In [29]:
print(matrix_4)

[[3 1 4]
 [0 3 2]
 [4 0 4]]


In [30]:
product = np.multiply(matrix_3, matrix_4)

In [31]:
print(product)

[[ 0  2  8]
 [ 0 12  4]
 [ 8  0 12]]
